/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{vue,js}'],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'error-container': '#ffdad6',
                'background': '#f7f9fb',
                'surface-tint': '#565e74',
                'tertiary': '#000000',
                'surface-container-lowest': '#ffffff',
                'primary-fixed': '#dae2fd',
                'surface-container-highest': '#e0e3e5',
                'on-secondary-fixed-variant': '#004395',
                'on-surface-variant': '#45464d',
                'error': '#ba1a1a',
                'on-secondary': '#ffffff',
                'primary-fixed-dim': '#bec6e0',
                'on-tertiary-fixed-variant': '#005321',
                'on-background': '#191c1e',
                'on-primary-container': '#7c839b',
                'tertiary-fixed-dim': '#4ae176',
                'surface-container-low': '#f2f4f6',
                'surface': '#f7f9fb',
                'surface-variant': '#e0e3e5',
                'on-primary-fixed': '#131b2e',
                'on-secondary-container': '#fefcff',
                'surface-container-high': '#e6e8ea',
                'inverse-surface': '#2d3133',
                'on-primary': '#ffffff',
                'tertiary-fixed': '#6bff8f',
                'on-primary-fixed-variant': '#3f465c',
                'secondary-fixed': '#d8e2ff',
                'on-secondary-fixed': '#001a42',
                'secondary': '#0058be',
                'secondary-container': '#2170e4',
                'inverse-on-surface': '#eff1f3',
                'on-error-container': '#93000a',
                'on-error': '#ffffff',
                'inverse-primary': '#bec6e0',
                'on-surface': '#191c1e',
                'on-tertiary-fixed': '#002109',
                'outline-variant': '#c6c6cd',
                'on-tertiary': '#ffffff',
                'secondary-fixed-dim': '#adc6ff',
                'surface-container': '#eceef0',
                'tertiary-container': '#002109',
                'primary': '#000000',
                'surface-bright': '#f7f9fb',
                'on-tertiary-container': '#009844',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            spacing: {
                xs: '4px',
                sm: '8px',
                md: '16px',
                lg: '24px',
                xl: '32px',
                base: '4px',
                gutter: '20px',
                'container-max': '1280px',
            },
            fontFamily: {
                'body-lg': ['Inter'],
                'headline-sm': ['Inter'],
                'headline-md': ['Inter'],
                'body-md': ['Inter'],
                'caption': ['Inter'],
                'display-lg': ['Inter'],
                'label-mono': ['JetBrains Mono'],
            },
            fontSize: {
                'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'caption': ['12px', { lineHeight: '16px', fontWeight: '500' }],
                'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'label-mono': ['13px', { lineHeight: '16px', fontWeight: '500' }],
            },
        },
    },
}
